package com.github.gbenroscience.sortmix.gui;

import com.github.gbenroscience.sortmix.Sortmix;
import com.github.gbenroscience.sortmix.bucketsorttunedquicksort.Grapher;
import static com.github.gbenroscience.sortmix.bucketsorttunedquicksort.Grapher.iterations; 
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.print.Book;
import java.awt.print.PageFormat;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author GBEMIRO
 */
public class AnalysisFrame extends javax.swing.JFrame implements Runnable {

    private Thread timer;
    private JFileChooser saveChooser;
    private Color color;

    /**
     * qcx Creates new form AnalysisFrame
     */
    public AnalysisFrame() {
        super("Sorting analysis system by G-Soft Inc. (08165779034, gbenroscience@yahoo.com)");
        initComponents();

        ButtonGroup grp = new ButtonGroup();

        grp.add(chartRadioButtonMenuItem);
        grp.add(graphRadioButtonMenuItem);

        grp.setSelected(graphRadioButtonMenuItem.getModel(), true);

        ButtonGroup bg = new ButtonGroup();
        bg.add(randomDataFloatCheckBoxMenuItem);
        bg.add(reverseSortedDataFloatCheckBoxMenuItem);
        bg.add(sortedDataFloatCheckBoxMenuItem);
        bg.add(partiallySortedDataFloatCheckBoxMenuItem);
        bg.add(binaryArrayDataFloatCheckBoxMenuItem);
        bg.add(randomDataIntCheckBoxMenuItem);
        bg.add(reverseSortedDataIntCheckBoxMenuItem);
        bg.add(sortedDataIntCheckBoxMenuItem);
        bg.add(partiallySortedDataIntCheckBoxMenuItem);
        bg.add(binaryArrayDataIntCheckBoxMenuItem);
        bg.add(digitsArray0_9_DataCheckBoxMenuItem);

        verticalScaleTextField.setText(graphPanel.getGrapher().getyStep() + "");
        horizontalScaleTextField.setText(graphPanel.getGrapher().getxStep() + "");
        gridSizeSpinner.setValue(graphPanel.getGrapher().getGridSize());
        numOfIterationsField.setText(Grapher.iterations + "");
        arraySizeField.setText(Grapher.getArraySize() + "");

        saveChooser = new JFileChooser();
        saveChooser.setVisible(false);
        saveChooser.setDialogTitle("Save Your Plot");

        saveChooser.setMultiSelectionEnabled(false);
        saveChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);

        applySettings();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        setLocation((dim.width - getWidth()) / 2, (dim.height - getHeight()) / 2);

        timer = new Thread(this);
        timer.start();

    }

    public static void setProgressValue(final int value) {
        double numOfAlgorithms = Sortmix.analysisFrame.graphPanel.grapher.graphObjectList.size();
        double processes = iterations * numOfAlgorithms;

        Runnable runner = new Runnable() {
            @Override
            public void run() {

            }
        };
        SwingUtilities.invokeLater(runner);

    }

    private void applySettings() {
        setGridSize();
        setShowGridLines();
        setVerticalScale();
        setHorizontalScale();
        setIterations();
    }

    /**
     * Retrieves the current values from the program objects to the controller
     * object. In essence, this is a notifier.
     */
    public void loadValuesToControllerFromProgram() {

        verticalScaleTextField.setText(String.valueOf(graphPanel.getGrapher().getyStep()));
        horizontalScaleTextField.setText(String.valueOf(graphPanel.getGrapher().getxStep()));

        gridSizeSpinner.setValue(graphPanel.getGrapher().getGridSize());

        showGridCheckBox.setSelected(graphPanel.getGrapher().isShowGridLines());

    }//end method

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        verticalScaleTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gridSizeSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        numOfIterationsField = new javax.swing.JTextField();
        arraySizeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        horizontalScaleTextField = new javax.swing.JTextField();
        showGridCheckBox = new javax.swing.JCheckBox();
        plotComparisonsButton = new javax.swing.JButton();
        randomBarColorCheckBox = new javax.swing.JCheckBox();
        progressLabel = new javax.swing.JLabel();
        graphPanel = new com.github.gbenroscience.sortmix.gui.GraphPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        graphRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        chartRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        tasksMenu = new javax.swing.JMenu();
        arraysdotSortCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        speedAndCacheBucketSortCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        memoryAndCacheBucketSortCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        speedOnlyCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        memoryOnlyCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        heapSortCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        insertionSortCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        mergeSortCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        quickSortCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        selectionSortCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        shellSortCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        randomDataFloatCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        reverseSortedDataFloatCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        sortedDataFloatCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        partiallySortedDataFloatCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        binaryArrayDataFloatCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        randomDataIntCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        reverseSortedDataIntCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        sortedDataIntCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        partiallySortedDataIntCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        binaryArrayDataIntCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        digitsArray0_9_DataCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        printMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        bgColorMenuItem = new javax.swing.JMenuItem();
        gridColorMenuItem = new javax.swing.JMenuItem();
        axesColorMenuItem = new javax.swing.JMenuItem();
        textColorMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        verticalScaleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalScaleTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Iterations Per Comparison                                 Vertical scale");

        gridSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 1, 100, 1));
        gridSizeSpinner.setToolTipText("Zoom graph");
        gridSizeSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(gridSizeSpinner, ""));
        gridSizeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gridSizeSpinnerStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Grid size(zoom)");

        printButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        printButton.setText("Print Graph");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        saveButton.setText("Save Graph");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        numOfIterationsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfIterationsFieldActionPerformed(evt);
            }
        });

        arraySizeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arraySizeFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Array size for comparison                                   Horizontal Scale");

        horizontalScaleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horizontalScaleTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arraySizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numOfIterationsField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verticalScaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horizontalScaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(printButton)
                .addGap(255, 255, 255))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(gridSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(6, 6, 6))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {printButton, saveButton});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {arraySizeField, numOfIterationsField});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numOfIterationsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verticalScaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arraySizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horizontalScaleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gridSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        showGridCheckBox.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        showGridCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        showGridCheckBox.setSelected(true);
        showGridCheckBox.setText("Show Grid?");
        showGridCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGridCheckBoxActionPerformed(evt);
            }
        });

        plotComparisonsButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        plotComparisonsButton.setText("Plot Comparisons");
        plotComparisonsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotComparisonsButtonActionPerformed(evt);
            }
        });

        randomBarColorCheckBox.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        randomBarColorCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        randomBarColorCheckBox.setText("Random Bar Colors On");
        randomBarColorCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomBarColorCheckBoxActionPerformed(evt);
            }
        });

        progressLabel.setFont(new java.awt.Font("Kartika", 3, 18)); // NOI18N
        progressLabel.setForeground(new java.awt.Color(255, 255, 255));
        progressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressLabel.setText("0%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(plotComparisonsButton)
                                .addGap(105, 105, 105))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(showGridCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(randomBarColorCheckBox)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(plotComparisonsButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(progressLabel)
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showGridCheckBox)
                    .addComponent(randomBarColorCheckBox))
                .addContainerGap())
        );

        /*GregorianCalendar expD =
        new GregorianCalendar(2015,Calendar.AUGUST,4);
        expD.set(Calendar.HOUR_OF_DAY, 0);
        expD.set(Calendar.MINUTE, 0);
        expD.set(Calendar.SECOND, 0);
        Calendar now = Calendar.getInstance();

        if(now.before(expD)){

        }
        else{
            JOptionPane.showMessageDialog(null, "Sofware expired!"
                + "Please contact G-Soft Inc. on 08165779034 "
                + "or gbenroscience@yahoo.com for the full version.");
            System.exit(0);
        }*/

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu3.setForeground(new java.awt.Color(0, 0, 153));
        jMenu3.setText("Graph Mode");
        jMenu3.setFont(new java.awt.Font("Kartika", 1, 12)); // NOI18N

        graphRadioButtonMenuItem.setFont(new java.awt.Font("Kartika", 1, 12)); // NOI18N
        graphRadioButtonMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        graphRadioButtonMenuItem.setSelected(true);
        graphRadioButtonMenuItem.setText("Graph");
        graphRadioButtonMenuItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                graphRadioButtonMenuItemItemStateChanged(evt);
            }
        });
        jMenu3.add(graphRadioButtonMenuItem);

        chartRadioButtonMenuItem.setFont(new java.awt.Font("Kartika", 1, 12)); // NOI18N
        chartRadioButtonMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        chartRadioButtonMenuItem.setSelected(true);
        chartRadioButtonMenuItem.setText("Chart");
        chartRadioButtonMenuItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chartRadioButtonMenuItemItemStateChanged(evt);
            }
        });
        jMenu3.add(chartRadioButtonMenuItem);

        jMenuBar1.add(jMenu3);

        tasksMenu.setForeground(new java.awt.Color(0, 0, 153));
        tasksMenu.setText("Compare Algorithms");
        tasksMenu.setFont(new java.awt.Font("Kartika", 1, 12)); // NOI18N

        arraysdotSortCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        arraysdotSortCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        arraysdotSortCheckBoxMenuItem.setText("Arrays.Sort(Java)--(A)");
        tasksMenu.add(arraysdotSortCheckBoxMenuItem);

        speedAndCacheBucketSortCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        speedAndCacheBucketSortCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        speedAndCacheBucketSortCheckBoxMenuItem.setText("BucketSort(Speed And Cache Optimized )--(BSCO)");
        tasksMenu.add(speedAndCacheBucketSortCheckBoxMenuItem);

        memoryAndCacheBucketSortCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        memoryAndCacheBucketSortCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        memoryAndCacheBucketSortCheckBoxMenuItem.setText("BucketSort(Memory And Cache Optimized )--(BMCO)");
        tasksMenu.add(memoryAndCacheBucketSortCheckBoxMenuItem);

        speedOnlyCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        speedOnlyCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        speedOnlyCheckBoxMenuItem.setText("BucketSort(Speed Only Optimized )--(BSO)");
        tasksMenu.add(speedOnlyCheckBoxMenuItem);

        memoryOnlyCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        memoryOnlyCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        memoryOnlyCheckBoxMenuItem.setText("BucketSort(Memory Only Optimized)--(BMO)");
        tasksMenu.add(memoryOnlyCheckBoxMenuItem);

        heapSortCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        heapSortCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        heapSortCheckBoxMenuItem.setText("HeapSort--(Hs)");
        tasksMenu.add(heapSortCheckBoxMenuItem);

        insertionSortCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        insertionSortCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        insertionSortCheckBoxMenuItem.setText("InsertionSort--(I)");
        tasksMenu.add(insertionSortCheckBoxMenuItem);

        mergeSortCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        mergeSortCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        mergeSortCheckBoxMenuItem.setText("MergeSort--(M)");
        tasksMenu.add(mergeSortCheckBoxMenuItem);

        quickSortCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        quickSortCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        quickSortCheckBoxMenuItem.setText("QuickSort--(Q)");
        tasksMenu.add(quickSortCheckBoxMenuItem);

        selectionSortCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        selectionSortCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        selectionSortCheckBoxMenuItem.setText("Selection Sort--(S)");
        tasksMenu.add(selectionSortCheckBoxMenuItem);

        shellSortCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        shellSortCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        shellSortCheckBoxMenuItem.setText("ShellSort--(Sh)");
        tasksMenu.add(shellSortCheckBoxMenuItem);

        jMenuBar1.add(tasksMenu);

        jMenu1.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1.setText("Type of Input Data");
        jMenu1.setFont(new java.awt.Font("Kartika", 1, 12)); // NOI18N

        randomDataFloatCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        randomDataFloatCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        randomDataFloatCheckBoxMenuItem.setSelected(true);
        randomDataFloatCheckBoxMenuItem.setText("RANDOM DATA--(FLOATS)");
        randomDataFloatCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomDataFloatCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(randomDataFloatCheckBoxMenuItem);

        reverseSortedDataFloatCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        reverseSortedDataFloatCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        reverseSortedDataFloatCheckBoxMenuItem.setText("REVERSE SORTED DATA--(FLOATS)");
        reverseSortedDataFloatCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseSortedDataFloatCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(reverseSortedDataFloatCheckBoxMenuItem);

        sortedDataFloatCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        sortedDataFloatCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        sortedDataFloatCheckBoxMenuItem.setText("SORTED DATA--(FLOATS)");
        sortedDataFloatCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortedDataFloatCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(sortedDataFloatCheckBoxMenuItem);

        partiallySortedDataFloatCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        partiallySortedDataFloatCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        partiallySortedDataFloatCheckBoxMenuItem.setText("PARTIALLY SORTED--(FLOATS)");
        partiallySortedDataFloatCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partiallySortedDataFloatCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(partiallySortedDataFloatCheckBoxMenuItem);

        binaryArrayDataFloatCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        binaryArrayDataFloatCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        binaryArrayDataFloatCheckBoxMenuItem.setText("BINARY ARRAY--(FLOATS)");
        binaryArrayDataFloatCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaryArrayDataFloatCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(binaryArrayDataFloatCheckBoxMenuItem);

        randomDataIntCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        randomDataIntCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        randomDataIntCheckBoxMenuItem.setText("RANDOM DATA--(INTS)");
        randomDataIntCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomDataIntCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(randomDataIntCheckBoxMenuItem);

        reverseSortedDataIntCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        reverseSortedDataIntCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        reverseSortedDataIntCheckBoxMenuItem.setText("REVERSE SORTED DATA--(INTS)");
        reverseSortedDataIntCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseSortedDataIntCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(reverseSortedDataIntCheckBoxMenuItem);

        sortedDataIntCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        sortedDataIntCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        sortedDataIntCheckBoxMenuItem.setText("SORTED DATA--(INTS)");
        sortedDataIntCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortedDataIntCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(sortedDataIntCheckBoxMenuItem);

        partiallySortedDataIntCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        partiallySortedDataIntCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        partiallySortedDataIntCheckBoxMenuItem.setText("PARTIALLY SORTED--(INTS)");
        partiallySortedDataIntCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partiallySortedDataIntCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(partiallySortedDataIntCheckBoxMenuItem);

        binaryArrayDataIntCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        binaryArrayDataIntCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        binaryArrayDataIntCheckBoxMenuItem.setText("BINARY ARRAY--(INTS)");
        binaryArrayDataIntCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaryArrayDataIntCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(binaryArrayDataIntCheckBoxMenuItem);

        digitsArray0_9_DataCheckBoxMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        digitsArray0_9_DataCheckBoxMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        digitsArray0_9_DataCheckBoxMenuItem.setText("ARRAY OF 0-9--(INTS)");
        digitsArray0_9_DataCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitsArray0_9_DataCheckBoxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(digitsArray0_9_DataCheckBoxMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 153));
        jMenu2.setText("Actions");
        jMenu2.setFont(new java.awt.Font("Kartika", 1, 12)); // NOI18N

        printMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        printMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        printMenuItem.setText("Print Graph");
        printMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(printMenuItem);

        saveMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        saveMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        saveMenuItem.setText("Save Graph");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(saveMenuItem);

        exitMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        exitMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(exitMenuItem);

        bgColorMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        bgColorMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        bgColorMenuItem.setText("Background Color");
        bgColorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColorMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(bgColorMenuItem);

        gridColorMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        gridColorMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        gridColorMenuItem.setText("Grid Color");
        gridColorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridColorMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(gridColorMenuItem);

        axesColorMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        axesColorMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        axesColorMenuItem.setText("Axes Color");
        axesColorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axesColorMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(axesColorMenuItem);

        textColorMenuItem.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        textColorMenuItem.setForeground(new java.awt.Color(0, 0, 153));
        textColorMenuItem.setText("Text Color");
        textColorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textColorMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(textColorMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(graphPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // Get a PrinterJob
        PrinterJob job = PrinterJob.getPrinterJob();
        // Create a landscape page format
        PageFormat landscape = job.defaultPage();
        landscape.setOrientation(PageFormat.PORTRAIT);
        // Set up a book
        Book bk = new Book();
        bk.append(graphPanel, landscape);
        // Pass the book to the PrinterJob
        job.setPageable(bk);
        // Put up the dialog box
        if (job.printDialog()) {
            // Print the job if the user didn't cancel printing
            try {
                job.print();
            } catch (Exception exc) { /* Handle Exception */ }
        }


    }//GEN-LAST:event_printButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        saveChooser.setVisible(true);
        int choice = saveChooser.showSaveDialog(this);

        if (choice == JFileChooser.APPROVE_OPTION) {

            String fileName = saveChooser.getSelectedFile().getName();
            fileName = fileName.endsWith(".jpg") ? fileName : fileName.concat(".jpg");
            File dir = saveChooser.getCurrentDirectory();
            File f = new File(dir.getAbsolutePath().concat("/" + fileName));

            try {
                BufferedImage graphImage = graphPanel.getGrapher().getImage();
                saveImage(graphImage, f.getAbsolutePath());

            } catch (NullPointerException exception) {
                JOptionPane.showMessageDialog(saveChooser, "Error in saving image");
            }//end catch
        }//end if
        else {
            JOptionPane.showMessageDialog(saveChooser, "Save Action Aborted");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void verticalScaleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalScaleTextFieldActionPerformed
        setVerticalScale();
        repaint();
    }//GEN-LAST:event_verticalScaleTextFieldActionPerformed

    private void showGridCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGridCheckBoxActionPerformed
        setShowGridLines();
        repaint();
    }//GEN-LAST:event_showGridCheckBoxActionPerformed

    private void gridSizeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gridSizeSpinnerStateChanged
        setGridSize();
    }//GEN-LAST:event_gridSizeSpinnerStateChanged

    private void numOfIterationsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfIterationsFieldActionPerformed

        try {
            int iterations = Integer.valueOf(numOfIterationsField.getText());
            graphPanel.grapher.setIterations(iterations);
            //plotComparisonsButton.doClick(200);
            graphPanel.getGrapher().setRefresh(true);
        } catch (NumberFormatException numErr) {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER A POSITIVE INTEGER!.", "BAD VALUE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_numOfIterationsFieldActionPerformed

    private void arraySizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arraySizeFieldActionPerformed
        try {
            int size = Integer.valueOf(arraySizeField.getText());
            Grapher.setArraySize(size);
            // plotComparisonsButton.doClick(200); 
            graphPanel.getGrapher().setRefresh(true);
        } catch (NumberFormatException numErr) {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER A POSITIVE INTEGER!.", "BAD VALUE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_arraySizeFieldActionPerformed

    private boolean busy = false;

    private void plotComparisonsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotComparisonsButtonActionPerformed
        if (busy) {
            JOptionPane.showMessageDialog(this, "Analysis in progress", "Appliation is busy!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Thread runner = new Thread(new Runnable() {

            @Override
            public void run() {
                busy = true;
                String text = getTitle();
                setTitle(text + "..Please wait!");

                //applySettings();     
                if (arraysdotSortCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(graphPanel.getGrapher().new Graphed(Grapher.Graphed.JAVA_ARRAYS_DOT_SORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.JAVA_ARRAYS_DOT_SORT);
                }
                if (speedAndCacheBucketSortCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(
                            graphPanel.getGrapher().new Graphed(Grapher.Graphed.CACHE_OPTIMIZATION_ENABLED_SPEED_OPTIMIZED_BUCKETSORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.CACHE_OPTIMIZATION_ENABLED_SPEED_OPTIMIZED_BUCKETSORT);
                }
                if (memoryAndCacheBucketSortCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(graphPanel.getGrapher().new Graphed(
                            Grapher.Graphed.CACHE_OPTIMIZATION_ENABLED_MEMORY_OPTIMIZED_BUCKETSORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.CACHE_OPTIMIZATION_ENABLED_MEMORY_OPTIMIZED_BUCKETSORT);
                }
                if (speedOnlyCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(
                            graphPanel.getGrapher().new Graphed(Grapher.Graphed.CACHE_OPTIMIZATION_DISABLED_SPEED_OPTIMIZED_BUCKETSORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.CACHE_OPTIMIZATION_DISABLED_SPEED_OPTIMIZED_BUCKETSORT);
                }
                if (memoryOnlyCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(
                            graphPanel.getGrapher().new Graphed(Grapher.Graphed.CACHE_OPTIMIZATION_DISABLED_MEMORY_OPTIMIZED_BUCKETSORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.CACHE_OPTIMIZATION_DISABLED_MEMORY_OPTIMIZED_BUCKETSORT);
                }
                if (heapSortCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(graphPanel.getGrapher().new Graphed(Grapher.Graphed.HEAPSORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.HEAPSORT);
                }
                if (insertionSortCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(graphPanel.getGrapher().new Graphed(Grapher.Graphed.INSERTIONSORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.INSERTIONSORT);
                }
                if (mergeSortCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(graphPanel.getGrapher().new Graphed(Grapher.Graphed.MERGESORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.MERGESORT);
                }
                if (quickSortCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(graphPanel.getGrapher().new Graphed(Grapher.Graphed.QUICKSORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.QUICKSORT);
                }
                if (selectionSortCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(graphPanel.getGrapher().new Graphed(Grapher.Graphed.SELECTIONSORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.SELECTIONSORT);
                }
                if (shellSortCheckBoxMenuItem.isSelected()) {
                    graphPanel.getGrapher().addGraphed(graphPanel.getGrapher().new Graphed(Grapher.Graphed.SHELLSORT, inputDataTypeAlgorithmSelect()));
                } else {
                    graphPanel.getGrapher().removeGraphed(Grapher.Graphed.SHELLSORT);
                }

                setTitle(text);
                graphPanel.getGrapher().setRefresh(true);
                repaint();
                busy = false;
            }
        });
        runner.setPriority(Thread.MAX_PRIORITY);
        runner.start();
    }//GEN-LAST:event_plotComparisonsButtonActionPerformed

    private void randomBarColorCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomBarColorCheckBoxActionPerformed
        setRandomBarColorsOn();
        repaint();
    }//GEN-LAST:event_randomBarColorCheckBoxActionPerformed

    private void randomDataFloatCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomDataFloatCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.ARRAY_OF_RANDOM_FLOATS);
            g.generator();
        }

    }//GEN-LAST:event_randomDataFloatCheckBoxMenuItemActionPerformed

    private void reverseSortedDataFloatCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseSortedDataFloatCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.ARRAY_OF_REVERSE_SORTED_FLOATS);
            g.generator();
        }
    }//GEN-LAST:event_reverseSortedDataFloatCheckBoxMenuItemActionPerformed

    private void sortedDataFloatCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortedDataFloatCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.ARRAY_OF_SORTED_FLOATS);
            g.generator();
        }
    }//GEN-LAST:event_sortedDataFloatCheckBoxMenuItemActionPerformed

    private void partiallySortedDataFloatCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partiallySortedDataFloatCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.ARRAY_OF_PARTIALLY_SORTED_FLOATS);
            g.generator();
        }
    }//GEN-LAST:event_partiallySortedDataFloatCheckBoxMenuItemActionPerformed

    private void binaryArrayDataFloatCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryArrayDataFloatCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.BINARY_ARRAY_OF_FLOATS);
            g.generator();
        }
    }//GEN-LAST:event_binaryArrayDataFloatCheckBoxMenuItemActionPerformed

    private void randomDataIntCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomDataIntCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.ARRAY_OF_RANDOM_INTS);
            g.generator();
        }
    }//GEN-LAST:event_randomDataIntCheckBoxMenuItemActionPerformed

    private void reverseSortedDataIntCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseSortedDataIntCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.ARRAY_OF_REVERSE_SORTED_INTS);
            g.generator();
        }
    }//GEN-LAST:event_reverseSortedDataIntCheckBoxMenuItemActionPerformed

    private void sortedDataIntCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortedDataIntCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.ARRAY_OF_SORTED_INTS);
            g.generator();
        }
    }//GEN-LAST:event_sortedDataIntCheckBoxMenuItemActionPerformed

    private void partiallySortedDataIntCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partiallySortedDataIntCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.ARRAY_OF_PARTIALLY_SORTED_INTS);
            g.generator();
        }
    }//GEN-LAST:event_partiallySortedDataIntCheckBoxMenuItemActionPerformed

    private void binaryArrayDataIntCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryArrayDataIntCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.BINARY_ARRAY_OF_INTS);
            g.generator();
        }
    }//GEN-LAST:event_binaryArrayDataIntCheckBoxMenuItemActionPerformed

    private void digitsArray0_9_DataCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitsArray0_9_DataCheckBoxMenuItemActionPerformed
        for (Grapher.Graphed g : graphPanel.grapher.graphObjectList) {
            g.setDataGeneratorType(Grapher.Graphed.ARRAY_OF_DIGITS);
            g.generator();
        }
    }//GEN-LAST:event_digitsArray0_9_DataCheckBoxMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        saveButton.doClick();
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void printMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMenuItemActionPerformed
        printButton.doClick();
    }//GEN-LAST:event_printMenuItemActionPerformed

    private void bgColorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgColorMenuItemActionPerformed
        color = JColorChooser.showDialog(this, "SET GRAPH BACKGROUND COLOR", color);
        graphPanel.getGrapher().setBgColor(color);
        repaint();
    }//GEN-LAST:event_bgColorMenuItemActionPerformed

    private void gridColorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridColorMenuItemActionPerformed
        color = JColorChooser.showDialog(this, "SET GRAPH GRID COLOR", color);
        graphPanel.getGrapher().setGridColor(color);
        repaint();
    }//GEN-LAST:event_gridColorMenuItemActionPerformed

    private void axesColorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axesColorMenuItemActionPerformed
        color = JColorChooser.showDialog(this, "SET GRAPH AXES COLOR", color);
        graphPanel.getGrapher().setMajorAxesColor(color);
        repaint();
    }//GEN-LAST:event_axesColorMenuItemActionPerformed

    private void textColorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textColorMenuItemActionPerformed
        color = JColorChooser.showDialog(this, "SET GRAPH TEXT COLOR", color);
        graphPanel.getGrapher().setTextColor(color);
        repaint();
    }//GEN-LAST:event_textColorMenuItemActionPerformed

    private void graphRadioButtonMenuItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_graphRadioButtonMenuItemItemStateChanged
        graphPanel.getGrapher().clearAllGraphed();
        deSelectAllAlgorithms();
        graphPanel.getGrapher().setPlotMode(Grapher.GRAPH);
        graphPanel.getGrapher().setHorizontalAxisLabel("Array Size");
        verticalScaleTextField.setText("0.01");
        horizontalScaleTextField.setText("100");
        setVerticalScale();
        setHorizontalScale();
        repaint();
    }//GEN-LAST:event_graphRadioButtonMenuItemItemStateChanged

    private void chartRadioButtonMenuItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chartRadioButtonMenuItemItemStateChanged
        graphPanel.getGrapher().clearAllGraphed();
        deSelectAllAlgorithms();
        graphPanel.getGrapher().setPlotMode(Grapher.BAR);
        graphPanel.getGrapher().setHorizontalAxisLabel("Sorting Algorithms");
        verticalScaleTextField.setText("1.0");
        horizontalScaleTextField.setText("1.0");
        setVerticalScale();
        setHorizontalScale();
        repaint();
    }//GEN-LAST:event_chartRadioButtonMenuItemItemStateChanged

    private void horizontalScaleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horizontalScaleTextFieldActionPerformed
        setHorizontalScale();
        repaint();
    }//GEN-LAST:event_horizontalScaleTextFieldActionPerformed

    /**
     * Saves a BufferedImage to the given file, pathname must not have any
     * periods "." in it except for the one before the format, i.e.
     * C:/images/fooimage.png
     *
     * @param img The image to save
     * @param ref The path to save it to.
     */
    public static void saveImage(BufferedImage img, String ref) {
        try {
            String format = (ref.endsWith(".png")) ? "png" : "jpg";
            ImageIO.write(img, format, new File(ref));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private int inputDataTypeAlgorithmSelect() {
        if (randomDataFloatCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.ARRAY_OF_RANDOM_FLOATS;
        } else if (reverseSortedDataFloatCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.ARRAY_OF_REVERSE_SORTED_FLOATS;
        }//ty
        else if (partiallySortedDataFloatCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.ARRAY_OF_PARTIALLY_SORTED_FLOATS;
        } else if (sortedDataFloatCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.ARRAY_OF_SORTED_FLOATS;
        } else if (binaryArrayDataFloatCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.BINARY_ARRAY_OF_FLOATS;
        } else if (randomDataIntCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.ARRAY_OF_RANDOM_INTS;
        } else if (reverseSortedDataIntCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.ARRAY_OF_REVERSE_SORTED_INTS;
        } else if (partiallySortedDataIntCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.ARRAY_OF_PARTIALLY_SORTED_INTS;
        } else if (sortedDataIntCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.ARRAY_OF_SORTED_INTS;
        } else if (binaryArrayDataIntCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.BINARY_ARRAY_OF_INTS;
        } else if (digitsArray0_9_DataCheckBoxMenuItem.isSelected()) {
            return Grapher.Graphed.ARRAY_OF_DIGITS;
        }
        return -1;

    }

    private void setVerticalScale() {
        try {
            double vertical = Double.valueOf(verticalScaleTextField.getText());
            graphPanel.getGrapher().setyStep(vertical);
            graphPanel.getGrapher().setRefresh(true);
        }//end try
        catch (NumberFormatException numErr) {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER A POSITIVE INTEGER!.", "BAD VALUE(S) On Vertical Settings", JOptionPane.ERROR_MESSAGE);
        }//end catch
    }//end method

    private void setHorizontalScale() {
        try {
            double horizontal = Double.valueOf(horizontalScaleTextField.getText());
            graphPanel.getGrapher().setxStep(horizontal);
            graphPanel.getGrapher().setRefresh(true);
        }//end try
        catch (NumberFormatException numErr) {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER A POSITIVE INTEGER!.", "BAD VALUE(S) On Horizontal Settings", JOptionPane.ERROR_MESSAGE);
        }//end catch
    }//end method

    private void setShowGridLines() {
        graphPanel.getGrapher().setShowGridLines(showGridCheckBox.isSelected());
    }

    private void setRandomBarColorsOn() {
        Grapher.setRandomSelectColor(randomBarColorCheckBox.isSelected());
        graphPanel.getGrapher().setRefresh(true);
    }

    private void setGridSize() {
        graphPanel.getGrapher().setGridSize((Integer) gridSizeSpinner.getValue());
        setTextFontSize();
    }

    void setIterations() {
        try {
            int iterations = Integer.valueOf(numOfIterationsField.getText());
            graphPanel.grapher.setIterations(iterations);
        } catch (NumberFormatException numErr) {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER A POSITIVE INTEGER!.", "BAD VALUE", JOptionPane.ERROR_MESSAGE);
        }
    }

    public GraphPanel getGraphPanel() {
        return graphPanel;
    }

    private void setTextFontSize() {
        try {
            Font font = graphPanel.getGrapher().getFont();
            double gridSize = graphPanel.getGrapher().getGridSize();
            double size = font.getSize();
            double next = Double.valueOf(gridSizeSpinner.getNextValue().toString());
            if (size > next) {
                size--;
            } else {
                size++;
            }
            graphPanel.getGrapher().setFont(new Font(font.getFamily(), font.getStyle(), (int) size));
        }//end try
        catch (NullPointerException nolian) {

        }
    }

    private boolean validateNumber(String number) {
        boolean isValid = true;
        try {
            double num = Double.valueOf(number);
            return true;
        } catch (NumberFormatException numErr) {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER A VALID NUMBER", "BAD VALUE", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    }

    private void selectAllAlgorithms() {
        boolean select = true;
        arraysdotSortCheckBoxMenuItem.setSelected(select);
        speedAndCacheBucketSortCheckBoxMenuItem.setSelected(select);
        memoryAndCacheBucketSortCheckBoxMenuItem.setSelected(select);
        speedOnlyCheckBoxMenuItem.setSelected(select);
        memoryOnlyCheckBoxMenuItem.setSelected(select);
        heapSortCheckBoxMenuItem.setSelected(select);
        insertionSortCheckBoxMenuItem.setSelected(select);
        mergeSortCheckBoxMenuItem.setSelected(select);
        quickSortCheckBoxMenuItem.setSelected(select);
        selectionSortCheckBoxMenuItem.setSelected(select);
        shellSortCheckBoxMenuItem.setSelected(select);
    }

    private void deSelectAllAlgorithms() {
        boolean select = false;
        arraysdotSortCheckBoxMenuItem.setSelected(select);
        speedAndCacheBucketSortCheckBoxMenuItem.setSelected(select);
        memoryAndCacheBucketSortCheckBoxMenuItem.setSelected(select);
        speedOnlyCheckBoxMenuItem.setSelected(select);
        memoryOnlyCheckBoxMenuItem.setSelected(select);
        heapSortCheckBoxMenuItem.setSelected(select);
        insertionSortCheckBoxMenuItem.setSelected(select);
        mergeSortCheckBoxMenuItem.setSelected(select);
        quickSortCheckBoxMenuItem.setSelected(select);
        selectionSortCheckBoxMenuItem.setSelected(select);
        shellSortCheckBoxMenuItem.setSelected(select);
    }
   private int getNumberOfSelectedAlgorithms() {
       int count = 0;
       if(arraysdotSortCheckBoxMenuItem.isSelected()){
           ++count;
       }
       if(speedAndCacheBucketSortCheckBoxMenuItem.isSelected()){
           ++count;
       }
       if(memoryAndCacheBucketSortCheckBoxMenuItem.isSelected()){
           ++count;
       }
        if(speedOnlyCheckBoxMenuItem.isSelected()){
           ++count;
       }
       if(memoryOnlyCheckBoxMenuItem.isSelected()){
           ++count;
       }
       if(heapSortCheckBoxMenuItem.isSelected()){
           ++count;
       }
        if(insertionSortCheckBoxMenuItem.isSelected()){
           ++count;
       }
       if(mergeSortCheckBoxMenuItem.isSelected()){
           ++count;
       }
        if(quickSortCheckBoxMenuItem.isSelected()){
           ++count;
       }
       if(selectionSortCheckBoxMenuItem.isSelected()){
           ++count;
       }
        if(shellSortCheckBoxMenuItem.isSelected()){
           ++count;
       }
      
        
     return count;
    }
    /**
     * Counts the number of tasks that have been completed.
     */
    public static int progressPointer = 0;
    public static boolean switched = false;
    @Override
    public void run() {
        Thread me = Thread.currentThread();
        boolean init = true;
        while (timer == me) {
            try {
                Thread.sleep(1000);
            }//end catch
            catch (InterruptedException exception) {

            }//end catch

            if (init && isVisible()) {
                if (graphPanel.getHeight() != this.getHeight()) {
                    Point pt = graphPanel.getGrapher().getLocationOfOrigin();
                    graphPanel.getGrapher().setLocationOfOrigin(pt.x + 1, pt.y);
  
              graphPanel.setSize( graphPanel.getWidth(), this.getHeight());
          
                    graphPanel.repaint();
                    init = false;
                }
            }//end if
if(busy){
 double tasks = getNumberOfSelectedAlgorithms();
double MAX_SIZE = Integer.parseInt( arraySizeField.getText() ) ;
  if(switched){ 
 switched = false;
 progressPointer++;
 }
double sizeBeingProcessed = (progressPointer * MAX_SIZE) + Grapher.arraySize;
 


 int percent = (int) (100 * sizeBeingProcessed/(tasks * MAX_SIZE) );

 progressLabel.setText("Analysis in progress: "+percent+"%");
}
         if(!busy){
        progressLabel.setText("0%");   
        progressPointer = 0;
        switched = false;
         }
 
 
 
 
 
            repaint();

        }//end while

    }//end method run.


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arraySizeField;
    private javax.swing.JCheckBoxMenuItem arraysdotSortCheckBoxMenuItem;
    private javax.swing.JMenuItem axesColorMenuItem;
    private javax.swing.JMenuItem bgColorMenuItem;
    private javax.swing.JCheckBoxMenuItem binaryArrayDataFloatCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem binaryArrayDataIntCheckBoxMenuItem;
    private javax.swing.JRadioButtonMenuItem chartRadioButtonMenuItem;
    private javax.swing.JCheckBoxMenuItem digitsArray0_9_DataCheckBoxMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private com.github.gbenroscience.sortmix.gui.GraphPanel graphPanel;
    private javax.swing.JRadioButtonMenuItem graphRadioButtonMenuItem;
    private javax.swing.JMenuItem gridColorMenuItem;
    private javax.swing.JSpinner gridSizeSpinner;
    private javax.swing.JCheckBoxMenuItem heapSortCheckBoxMenuItem;
    private javax.swing.JTextField horizontalScaleTextField;
    private javax.swing.JCheckBoxMenuItem insertionSortCheckBoxMenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBoxMenuItem memoryAndCacheBucketSortCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem memoryOnlyCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem mergeSortCheckBoxMenuItem;
    private javax.swing.JTextField numOfIterationsField;
    private javax.swing.JCheckBoxMenuItem partiallySortedDataFloatCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem partiallySortedDataIntCheckBoxMenuItem;
    private javax.swing.JButton plotComparisonsButton;
    private javax.swing.JButton printButton;
    private javax.swing.JMenuItem printMenuItem;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JCheckBoxMenuItem quickSortCheckBoxMenuItem;
    private javax.swing.JCheckBox randomBarColorCheckBox;
    private javax.swing.JCheckBoxMenuItem randomDataFloatCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem randomDataIntCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem reverseSortedDataFloatCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem reverseSortedDataIntCheckBoxMenuItem;
    private javax.swing.JButton saveButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JCheckBoxMenuItem selectionSortCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem shellSortCheckBoxMenuItem;
    private javax.swing.JCheckBox showGridCheckBox;
    private javax.swing.JCheckBoxMenuItem sortedDataFloatCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem sortedDataIntCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem speedAndCacheBucketSortCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem speedOnlyCheckBoxMenuItem;
    private javax.swing.JMenu tasksMenu;
    private javax.swing.JMenuItem textColorMenuItem;
    private javax.swing.JTextField verticalScaleTextField;
    // End of variables declaration//GEN-END:variables
}
