package com.github.gbenroscience.sortmix.gui;


import com.github.gbenroscience.sortmix.bucketsorttunedquicksort.Grapher;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GBEMIRO
 */
public class GraphPanel extends javax.swing.JPanel implements Printable{
    Grapher grapher;
    
    /**
     * Set this object's attributes
     * when the pointerPressed method is called.
     */
    private Point startCoords=new Point();
    /**
     * Set this object's attributes
     * when the pointerReleased method is called.
     */
    private Dimension shiftCoords=new Dimension();
    /** Creates new form GraphPaper */
    /**
     * Creates new form GraphPanel
     */
    public GraphPanel() {
        initComponents();
        setSize(getPreferredSize());
        grapher = new Grapher(true, true,10,Color.green, Color.blue,15, 5, 0, 20000,
       1,1, new Font("Arial Bold",Font.PLAIN,15),this );
    }

    @Override
    public void setSize(int width, int height) {
        super.setSize(width, height); //To change body of generated methods, choose Tools | Templates.
        if(grapher!=null){
        grapher.setWidth(width);
        grapher.setHeight(height);
        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        try{
            setToolTipText( String.valueOf( grapher.convertScreenPointToGraphPoint(new Point(evt.getX(),evt.getY())) ) );
        }//end try
        catch(NullPointerException nolian){
        }        
    }//GEN-LAST:event_formMouseMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
Point evtLoc=evt.getPoint();

        shiftCoords = new Dimension( (int) (evtLoc.x - startCoords.x), (int) (evtLoc.y - startCoords.y) );
        Point p = grapher.getLocationOfOrigin();
        grapher.setLocationOfOrigin( new Point( p.x+shiftCoords.width,p.y+shiftCoords.height ) );
        startCoords.x = evtLoc.x;
        startCoords.y = evtLoc.y;
 repaint();        
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
Point evtLoc=evt.getPoint();
        startCoords.x = evtLoc.x;
        startCoords.y = evtLoc.y;        
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
Point evtLoc=evt.getPoint();
        startCoords.x = evtLoc.x;
        startCoords.y = evtLoc.y;        
    }//GEN-LAST:event_formMouseReleased

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
      Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
      setCursor(cursor);        
    }//GEN-LAST:event_formMouseEntered

    public void setGrapher(Grapher grapher) {
        this.grapher = grapher;
    }
    public Grapher getGrapher() {
        return grapher;
    }

//ty
        @Override
    public void paintComponent(Graphics g){
        try{
        super.paintComponent(g);
        grapher.draw();
        g.drawImage(grapher.getImage(),0,0,this);
        }
        catch(NullPointerException nol){
//
        }
    }//end method
    
    
     public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {

BufferedImage img = grapher.getImage();
Graphics2D g2D = (Graphics2D) graphics;
 g2D.drawImage(img, 0,0,img.getWidth(),img.getHeight(), this );
        return Printable.PAGE_EXISTS;
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}